---
title: "solution4"
output: html_notebook
---
```{r}
#Example in the slide
#USArrest, cluster
install.packages("fpc") #install the fpc package
library(cluster) #input cluster package
library(fpc)
data("USArrests") #input the dataset
dim(USArrests) #check the data dimension
summary(USArrests) #overview
USArrests[1:3,] #output 1:3 rows
```

```{r}
#Origin
set.seed(123)
kmoriginal=kmeans(USArrests,4) #"4"is the number of cluster
plotcluster(USArrests,kmoriginal$cluster,las=1,main="Original")
#kmoriginal$cluster means extract cluster from kmoriginal, main="headline"
```


```{r}
#scaled
set.seed(123) 
scaled=scale(USArrests) #scale the data
kmscaled=kmeans(scaled,4) 
plotcluster(scaled,kmscaled$cluster, las=1,main="Scaled")
```


```{r}
#draw circle
clusplot(USArrests, kmoriginal$cluster, color=T, shade=T, labels=2, lines=0, las=1,cex=0.7)
clusplot(USArrests, kmscaled$cluster, color=T, shade=T, labels=2, lines=0, las=1,cex=0.7)
```
```{r}
#Exercise4
#Problem1
library(cluster)
library(fpc)
data("USArrests")
scaled <- scale(USArrests)
```


```{r}
#kmoriginal
kmoriginal=pam(USArrests,4) #pam() is k-medoids function
plotcluster(USArrests,kmoriginal$cluster,las=1,main="Original")
```


```{r}
#kmscaled
kmscaled=pam(scaled,4)
plotcluster(scaled,kmscaled$cluster,las=1,main="Scaled")
```


```{r}
#alternative ploting
library(factoextra) #install.package("")
fviz_cluster(kmoriginal,repel=T)
```


```{r}
fviz_cluster(kmscaled, repel = T)
```
```{r}
#seeking for best k
kmscaled2=pamk(scaled)
plotcluster(scaled,kmscaled2$pamobject$cluster,las=1,main="Scaled")
```

```{r}
fviz_cluster(kmscaled2$pamobject, repel = T)
```
Here is one alternative given for plotting clusters by principal components with a plot based on ggplot. As
mentioned in the lecture you need to specify the number of clusters. There is a build-in function in pamk
[fpc package] that seeks the optimal number of k. For this data it selects 2 clusters instead of the 4 we used.
Scaling is again leading to different results and hence it should always be done at first.
```{r}
#problem(b)
original.avg = agnes(x=USArrests, diss = FALSE, method = "average") #hierarchical clustering
dend.original.avg = as.dendrogram(original.avg) #generate dendograms' data
scaled.avg = agnes(x=scaled, diss = FALSE, method = "average")
dend.scaled.avg = as.dendrogram(scaled.avg)
original.comp = agnes(x=USArrests, diss = FALSE, method = "complete")
dend.original.comp = as.dendrogram(original.comp)
scaled.comp = agnes(x=scaled, diss = FALSE, method = "complete")
dend.scaled.comp = as.dendrogram(scaled.comp)
original.sing = agnes(x=USArrests, diss = FALSE, method = "single")
dend.original.sing = as.dendrogram(original.sing)
scaled.sing = agnes(x=scaled, diss = FALSE, method = "single")
dend.scaled.sing = as.dendrogram(scaled.sing)
plot(dend.scaled.avg,main="Scaled average")
#plot(dend.scaled.comp,main="Scaled complete")
#plot(dend.scaled.sing,main="Scaled single")
#plot(dend.original.avg,main="Original average")
#plot(dend.original.comp,main="Original complete")
#plot(dend.original.sing,main="Original single")
```
